version: '3'
services:
  salz-db:
    build: salz-db
    ports:
      - "5432:5432"
    expose:
      - "5432"
        # environment:
        #   - POSTGRES_DB=postgres
        #   - POSTGRES_USER=postgres
        #   - POSTGRES_PASSWORD=mysecretpassword
    env_file:
      - ./salz-db.env
  salz-api:
    build: salz-api
    depends_on:
      - salz-db
    ports:
      - "8080:8080"
    env_file:
      - ./salz-api.env
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=mysecretpassword
      - POSTGRES_PORT=5432
      - POSTGRES_HOST=salz-db
      - BOTLOCATION=/data
    volumes:
      - "botfiles:/data"
  salz-engine:
    build: salz-engine
    depends_on:
      - salz-db
    env_file:
      - ./salz-engine.env
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=mysecretpassword
      - POSTGRES_PORT=5432
      - POSTGRES_HOST=salz-db
    volumes:
      - "botfiles:/data"
  salz-web:
    build: salz-web
    env_file:
      - ./salz-web.env
    ports:
      - "3000:3000"
    expose:
      - "3000"

volumes:
  botfiles:
