version: '3'
services:
  salz-db:
    build: Database
    ports:
      - "5432:5432"
    expose:
      - "5432"
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=mysecretpassword
  salz-api:
    build: salz-api
    depends_on:
      - salz-db
    ports:
      - "8080:8080"
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=mysecretpassword
      - POSTGRES_PORT=5432
      - POSTGRES_HOST=salz-db
