version: '3'
services:
  salz-db:
    build: Database
    ports:
      - "5432:5432"
    expose:
      - "5432"
  salz-api:
    build: salz-api
    depends_on:
      - salz-db
    ports:
      - "8080:8080"
